"""Add last_login to User model

Revision ID: 691300f860d2
Revises: f0750eb4fd9e
Create Date: 2024-10-20 16:34:04.800828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '691300f860d2'
down_revision = 'f0750eb4fd9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###
