"""Add pin column to User model

Revision ID: f0750eb4fd9e
Revises: 91354e5746dc
Create Date: 2024-10-17 18:39:26.328138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0750eb4fd9e'
down_revision = '91354e5746dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('security_question', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('security_answer', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('setup_completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('setup_completed')
        batch_op.drop_column('security_answer')
        batch_op.drop_column('security_question')
        batch_op.drop_column('pin')

    # ### end Alembic commands ###
